# welcome to the eda of my data analytic project

In [38]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [39]:
df=pd.read_csv("C:/Users/ASUS/Desktop/Banking.csv")

In [40]:
df.head(10)

,Client ID,Name,Age,Location ID,Joined Bank,Banking Contact,Nationality,Occupation,Fee Structure,Loyalty Classification,...,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,1
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,1,2
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,2,3
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,1,4
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,2,5
5,IND78532,Samuel Hudson,23,13204,07-02-2019,Douglas Tucker,American,Help Desk Technician,High,Silver,...,1307269.41,745627.74,238310.37,15615.18,1556031.06,1,2,1,1,6
6,IND95683,Timothy Alexander,46,42910,02-06-2002,Douglas Tucker,Asian,Account Coordinator,High,Gold,...,41200.18,60588.50,24639.33,3045.78,154111.62,1,1,1,2,7
7,IND40785,Carl Martin,78,6127,03-11-2000,Steve Diaz,European,Automation Specialist II,Mid,Gold,...,156983.13,53889.73,46813.78,51979.19,1171456.68,0,2,2,2,8
8,IND13570,Philip Day,67,32656,07-04-2015,Bruce Butler,Asian,Software Test Engineer II,High,Silver,...,1242347.22,328334.62,279528.12,27125.28,464560.28,0,1,2,2,9
9,IND53299,Jason Sims,51,28340,20-11-1995,Joe Price,European,Geologist III,Mid,Silver,...,317246.67,111532.03,115869.39,48043.52,908583.94,2,1,3,1,10

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Client ID                 3000 non-null   object
 1   Name                      3000 non-null   object
 2   Age                       3000 non-null   int64
 3   Location ID               3000 non-null   int64
 4   Joined Bank               3000 non-null   object
 5   Banking Contact           3000 non-null   object
 6   Nationality               3000 non-null   object
 7   Occupation                3000 non-null   object
 8   Fee Structure             3000 non-null   object
 9   Loyalty Classification    3000 non-null   object
 10  Estimated Income          3000 non-null   float64
 11  Superannuation Savings    3000 non-null   float64
 12  Amount of Credit Cards    3000 non-null   int64
 13  Credit Card Balance       3000 non-null   float64
 14  Bank Loans                3000 non-null   float64
 15  Bank Deposits             3000 non-null   float64
 16  Checking Accounts         3000 non-null   float64
 17  Saving Accounts           3000 non-null   float64
 18  Foreign Currency Account  3000 non-null   float64
 19  Business Lending          3000 non-null   float64
 20  Properties Owned          3000 non-null   int64
 21  Risk Weighting            3000 non-null   int64
 22  BRId                      3000 non-null   int64
 23  GenderId                  3000 non-null   int64
 24  IAId                      3000 non-null   int64
dtypes: float64(9), int64(8), object(8)
memory usage: 586.1+ KB

In [42]:
df.describe(include='all')

,Client ID,Name,Age,Location ID,Joined Bank,Banking Contact,Nationality,Occupation,Fee Structure,Loyalty Classification,...,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
count,3000,3000,3000.000000,3000.000000,3000,3000,3000,3000,3000,3000,...,3.000000e+03,3.000000e+03,3.000000e+03,3000.000000,3.000000e+03,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
unique,2940,2913,NaN,NaN,2579,49,5,195,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,IND48103,Jeremy Alexander,NaN,NaN,19-06-2020,Ernest Rivera,European,Associate Professor,High,Jade,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3,2,NaN,NaN,4,77,1309,28,1476,1331,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,51.039667,21563.323000,NaN,NaN,NaN,NaN,NaN,NaN,...,6.715602e+05,3.210929e+05,2.329084e+05,29883.529993,8.667598e+05,1.518667,2.249333,2.559333,1.504000,10.425333
std,NaN,NaN,19.854760,12462.273017,NaN,NaN,NaN,NaN,NaN,NaN,...,6.457169e+05,2.820796e+05,2.300078e+05,23109.924010,6.412303e+05,1.102145,1.131191,1.007713,0.500067,5.988242
min,NaN,NaN,17.000000,12.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,45.000000,0.000000e+00,0.000000,1.000000,1.000000,1.000000,1.000000
25%,NaN,NaN,34.000000,10803.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,2.044004e+05,1.199475e+05,7.479440e+04,11916.542500,3.748251e+05,1.000000,1.000000,2.000000,1.000000,5.000000
50%,NaN,NaN,51.000000,21129.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,4.633165e+05,2.428157e+05,1.640866e+05,24341.190000,7.113147e+05,2.000000,2.000000,3.000000,2.000000,10.000000
75%,NaN,NaN,69.000000,32054.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,9.427546e+05,4.348749e+05,3.155750e+05,41966.392500,1.185110e+06,2.000000,3.000000,3.000000,2.000000,15.000000
max,NaN,NaN,85.000000,43369.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,3.890598e+06,1.969923e+06,1.724118e+06,124704.870000,3.825962e+06,3.000000,5.000000,4.000000,2.000000,22.000000

In [43]:
df.isnull().sum()

Client ID                   0
Name                        0
Age                         0
Location ID                 0
Joined Bank                 0
Banking Contact             0
Nationality                 0
Occupation                  0
Fee Structure               0
Loyalty Classification      0
Estimated Income            0
Superannuation Savings      0
Amount of Credit Cards      0
Credit Card Balance         0
Bank Loans                  0
Bank Deposits               0
Checking Accounts           0
Saving Accounts             0
Foreign Currency Account    0
Business Lending            0
Properties Owned            0
Risk Weighting              0
BRId                        0
GenderId                    0
IAId                        0
dtype: int64

In [44]:
df.columns=df.columns.str.lower()

In [45]:
df.columns

Index(['client id', 'name', 'age', 'location id', 'joined bank',
       'banking contact', 'nationality', 'occupation', 'fee structure',
       'loyalty classification', 'estimated income', 'superannuation savings',
       'amount of credit cards', 'credit card balance', 'bank loans',
       'bank deposits', 'checking accounts', 'saving accounts',
       'foreign currency account', 'business lending', 'properties owned',
       'risk weighting', 'brid', 'genderid', 'iaid'],
      dtype='object')

In [46]:
df.columns=df.columns.str.replace(" ","_")

In [47]:
df.columns

Index(['client_id', 'name', 'age', 'location_id', 'joined_bank',
       'banking_contact', 'nationality', 'occupation', 'fee_structure',
       'loyalty_classification', 'estimated_income', 'superannuation_savings',
       'amount_of_credit_cards', 'credit_card_balance', 'bank_loans',
       'bank_deposits', 'checking_accounts', 'saving_accounts',
       'foreign_currency_account', 'business_lending', 'properties_owned',
       'risk_weighting', 'brid', 'genderid', 'iaid'],
      dtype='object')

In [48]:
df['genderid']

0       1
1       1
2       2
3       1
4       2
       ..
2995    2
2996    2
2997    2
2998    2
2999    2
Name: genderid, Length: 3000, dtype: int64

In [49]:
df['gender']=df['genderid'].apply(lambda x:'male' if x==1 else 'female')

In [50]:
df['gender']

0         male
1         male
2       female
3         male
4       female
         ...
2995    female
2996    female
2997    female
2998    female
2999    female
Name: gender, Length: 3000, dtype: object

In [51]:
df.drop('genderid',axis=1)

,client_id,name,age,location_id,joined_bank,banking_contact,nationality,occupation,fee_structure,loyalty_classification,...,bank_deposits,checking_accounts,saving_accounts,foreign_currency_account,business_lending,properties_owned,risk_weighting,brid,iaid,gender
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,male
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,2,male
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,3,female
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,4,male
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,5,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,IND66827,Earl Hall,82,8760,09-10-2014,Joshua Bennett,American,Accounting Assistant III,High,Gold,...,1089957.03,532867.88,657849.62,12947.31,1238859.91,1,3,3,4,female
2996,IND40556,Billy Williamson,44,32837,05-02-2009,Dennis Ruiz,European,Paralegal,Mid,Gold,...,136891.32,56581.74,93195.61,23205.69,277171.07,1,2,3,5,female
2997,IND72414,Victor Black,70,36088,29-12-2009,Joshua Ryan,American,Statistician IV,Low,Jade,...,214860.89,158726.06,35539.15,30291.81,502947.22,2,2,3,6,female
2998,IND46652,Andrew Ford,56,24871,13-02-2006,Nicholas Cunningham,European,Human Resources Assistant III,Mid,Jade,...,742630.22,404638.26,56411.33,6413.14,1538368.60,3,1,3,7,female
2999,IND40216,Amy Nguyen,79,38518,08-12-2005,Joe Hanson,American,Biostatistician III,High,Jade,...,65617.66,77769.08,32371.38,8992.36,329412.55,1,1,3,8,female

In [52]:
df.drop('bank_type',axis=1)

KeyError: "['bank_type'] not found in axis"

In [ ]:
df.columns

In [ ]:
df['bank_type']=df['brid'].replace(lambda x:'retail' if x==1 else 'institutional' if x==2 else 'public' if x==3 else 'commnercial' if x==4

In [ ]:
df['bank_type'] = df['brid'].map({
    1: 'retail',
    2: 'institutional',
    3: 'public',
    4: 'commercial'
}).fillna('unknown')

In [ ]:
df.head()

In [ ]:
df['investment_advisor'] = df['iaid'].map({    1:'Victor Dean',
2:	'Jeremy Porter',
3:	'Ernest Knight',
4:	'Eric Shaw',
5:	'Kevin Kim',
6:	'Victor Rogers',
7:	'Eugene Cunningham',
8:	'Joe Carroll',
9:	'Steve Sanchez',
10:	'Lawrence Sanchez',
11:	'Peter Castillo',
12:	'Victor Gutierrez',
13:	'Daniel Carroll',
14:	'Carl Anderson',
15:	'Nicholas Ward',
16:	'Fred Bryant',
17:	'Ryan Taylor',
18:	'Sean Vasquez',
19:	'Nicholas Morrison',
20:	'Jack Phillips',
21:	'Juan Ramirez',
22:	'Gregory Boyd'

}).fillna('unknown')

In [ ]:
df.columns

In [ ]:
df['estimated_income'].value_counts()

In [54]:
bins=[0,100000,300000,float("inf")]
labels=['low','med','high']
df['income_band']=pd.cut(df['estimated_income'],bins=bins,labels=labels,right=False)

In [55]:
df['income_band']

0        low
1        med
2        med
3       high
4        med
        ...
2995     med
2996     low
2997     low
2998     med
2999     low
Name: income_band, Length: 3000, dtype: category
Categories (3, object): ['low' < 'med' < 'high']

In [ ]:
df['income_band'].value_counts().plot(kind='bar')

In [ ]:
df['gender'].value_counts().plot(kind='bar')
plt.show()

df['bank_type'].value_counts().plot(kind='bar')
plt.show()

In [ ]:
for i,predictor in enumerate(df['brid','gender','iaid','amount_of_credit_cards','nationality','occupation','fee_structure','loyal_classification']):
    plt.figure(i)
    sns.countplot(data=df,x=predictor,hue='gender_id')

In [ ]:
columns = ['brid', 'gender', 'iaid', 'amount_of_credit_card',
           'nationality', 'occupation', 'fee_structure', 'loyal_classification']

for i, predictor in enumerate(columns):
    sns.countplot(data=df, x=predictor, hue='genderid')

In [ ]:
df

In [ ]:
for i, predictor in enumerate(df[["brid", "genderid", "iaid", "amount_of_credit_cards", "nationality", "occupation", "fee_structure", "loyalty_classification", "properties_owned", "risk_weighting", "income_band"]].columns):
    plt.figure(i)
    sns.countplot(data=df, x=predictor)

In [ ]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

username = "root"
password = quote_plus("1989211ss@V")
host = "localhost"
port = "3306"

# connect to MySQL server (no database yet)
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}")

In [ ]:
with engine.connect() as conn:
    conn.execute(text("CREATE DATABASE IF NOT EXISTS mydata;"))

In [ ]:
database = "mydata"
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [ ]:
df.to_sql("mytable", engine, if_exists="replace", index=False)

import pandas as pd
result = pd.read_sql("SELECT * FROM mytable LIMIT 5;", engine)

print(result)

In [53]:
df.columns

Index(['client_id', 'name', 'age', 'location_id', 'joined_bank',
       'banking_contact', 'nationality', 'occupation', 'fee_structure',
       'loyalty_classification', 'estimated_income', 'superannuation_savings',
       'amount_of_credit_cards', 'credit_card_balance', 'bank_loans',
       'bank_deposits', 'checking_accounts', 'saving_accounts',
       'foreign_currency_account', 'business_lending', 'properties_owned',
       'risk_weighting', 'brid', 'genderid', 'iaid', 'gender'],
      dtype='object')